##The website title
name: League of Automated Nations
##Markdown processor
markdown: kramdown
##syntax highlighter. 
highlighter: rouge

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://example.com
sass:
  sass_dir: _sass
  style: :compressed

##The website description (to be used in meta tags)
description: Alliance tracking for Screeps, the game that plays itself.
##Some frequently used keywords on your website
keywords: screeps, mmo, programming

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
ga_id: UA-84882486-1
ga_domain: auto

##Some commonly used links
links:
  github: LeagueOfAutomatedNations

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: leaguelogo.jpg
##comment this if you want full width posts with no sidebar
sidebar: on
